import { createAction } from 'redux-act'

export const addBuyChunks = createAction('ADD_BUY_CHUNKS')
export const addChunkedCurrency = createAction('ADD_CHUNKED_CURRENCY')
export const addSellChunks = createAction('ADD_SELL_CHUNKS')
export const addStats = createAction('ADD_STATS')
export const botMessage = createAction('BOT_MESSAGE')
export const convertCurrencyToChunks = createAction('CONVERT_CURRENCY_TO_CHUNKS')
export const coverBuy = createAction('COVER_BUY')
export const coverSell = createAction('COVER_SELL')
export const doBuy = createAction('DO_BUY')
export const doSell = createAction('DO_SELL')
export const getCurrentPair = createAction('GET_CURRENT_PAIR')
export const newTrade = createAction('NEW_TRADE')
export const orderBookModify = createAction('ORDER_BOOK_MODIFY')
export const orderBookRemove = createAction('ORDER_BOOK_REMOVE')
export const setCurrency = createAction('SET_CURRENCY')
export const setCurrencyPair = createAction('SET_CURRENCY_PAIR')
export const setFreeCurrencyIsset = createAction('SET_FREE_CURRENCY_ISSET')
export const setTrends = createAction('SET_TRENDS')
export const updateWallet = createAction('UPDATE_WALLET')
export const setChunkAmount = createAction('SET_CHUNK_AMOUNT')
