import { createAction } from 'redux-act'

export const addChunks = createAction('ADD_CHUNKS')
export const addMessage = createAction('ADD_MESSAGE', (type, message) => ({ type, message }))
export const addStats = createAction('ADD_STATS')
export const addStatsDynamics = createAction('ADD_STATS_DYNAMICS')
export const buyFailure = createAction('BUY_FAILURE')
export const buySuccess = createAction('BUY_SUCCESS')
export const cleanChunksType = createAction('CLEAN_CHUNKS_TYPE')
export const doBuy = createAction('DO_BUY')
export const doSell = createAction('DO_SELL')
export const getCurrentPair = createAction('GET_CURRENT_PAIR')
export const newTrade = createAction('NEW_TRADE')
export const orderBookModify = createAction('ORDER_BOOK_MODIFY')
export const orderBookRemove = createAction('ORDER_BOOK_REMOVE')
export const removeChunk = createAction('REMOVE_CHUNK')
export const replaceChunksAmount = createAction('REPLACE_CHUNKS_AMOUNT')
export const requestInvalidateChunks = createAction('REQUEST_INVALIDATE_CHUNKS')
export const requestNewChunks = createAction('REQUEST_NEW_CHUNKS')
export const sellFailure = createAction('SELL_FAILURE')
export const sellSuccess = createAction('SELL_SUCCESS')
export const setChunkAmount = createAction('SET_CHUNK_AMOUNT')
export const setBalanceValues = createAction('SET_BALANCE_VOLUMES')
export const setBuyProfitThreshold = createAction('SET_BUY_PROFIT_THRESHOLD')
export const setCurrency = createAction('SET_CURRENCY')
export const setCurrencyPair = createAction('SET_CURRENCY_PAIR')
export const setDynamicsTotal = createAction('SET_DYNAMICS_TOTAL')
export const setFreeCurrencies = createAction('SET_FREE_CURRENCIES')
export const setObsoleteThreshold = createAction('SET_OBSOLETE_THRESHOLD')
export const setSellProfitThreshold = createAction('SET_SELL_PROFIT_THRESHOLD')
export const setStopTrade = createAction('SET_STOP_TRADE')
export const setTrends = createAction('SET_TRENDS')
export const stopTransactionsType = createAction('STOP_TRANSACTIONS_TYPE', (type, status) => ({ type, status }))
export const updateWallet = createAction('UPDATE_WALLET')
